/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TipBBSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dislike"
      | "latestPostId"
      | "like"
      | "likeWithTip"
      | "post"
      | "posts"
      | "reply"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Disliked"
      | "Liked"
      | "Posted"
      | "Replied"
      | "Tipped"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "dislike",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestPostId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "like", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "likeWithTip",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "post", values: [string]): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "reply",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "dislike", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestPostId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "like", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "likeWithTip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "post", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reply", data: BytesLike): Result;
}

export namespace DislikedEvent {
  export type InputTuple = [postId: BigNumberish, user: AddressLike];
  export type OutputTuple = [postId: bigint, user: string];
  export interface OutputObject {
    postId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LikedEvent {
  export type InputTuple = [postId: BigNumberish, user: AddressLike];
  export type OutputTuple = [postId: bigint, user: string];
  export interface OutputObject {
    postId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    user: AddressLike,
    text: string
  ];
  export type OutputTuple = [postId: bigint, user: string, text: string];
  export interface OutputObject {
    postId: bigint;
    user: string;
    text: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepliedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    user: AddressLike,
    parentPostId: BigNumberish,
    text: string
  ];
  export type OutputTuple = [
    postId: bigint,
    user: string,
    parentPostId: bigint,
    text: string
  ];
  export interface OutputObject {
    postId: bigint;
    user: string;
    parentPostId: bigint;
    text: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TippedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    user: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [postId: bigint, user: string, value: bigint];
  export interface OutputObject {
    postId: bigint;
    user: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TipBBS extends BaseContract {
  connect(runner?: ContractRunner | null): TipBBS;
  waitForDeployment(): Promise<this>;

  interface: TipBBSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dislike: TypedContractMethod<[postId: BigNumberish], [void], "nonpayable">;

  latestPostId: TypedContractMethod<[], [bigint], "view">;

  like: TypedContractMethod<[postId: BigNumberish], [void], "nonpayable">;

  likeWithTip: TypedContractMethod<[postId: BigNumberish], [void], "payable">;

  post: TypedContractMethod<[text: string], [void], "nonpayable">;

  posts: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  reply: TypedContractMethod<
    [parentPostId: BigNumberish, text: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dislike"
  ): TypedContractMethod<[postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "latestPostId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "like"
  ): TypedContractMethod<[postId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "likeWithTip"
  ): TypedContractMethod<[postId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "post"
  ): TypedContractMethod<[text: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "reply"
  ): TypedContractMethod<
    [parentPostId: BigNumberish, text: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Disliked"
  ): TypedContractEvent<
    DislikedEvent.InputTuple,
    DislikedEvent.OutputTuple,
    DislikedEvent.OutputObject
  >;
  getEvent(
    key: "Liked"
  ): TypedContractEvent<
    LikedEvent.InputTuple,
    LikedEvent.OutputTuple,
    LikedEvent.OutputObject
  >;
  getEvent(
    key: "Posted"
  ): TypedContractEvent<
    PostedEvent.InputTuple,
    PostedEvent.OutputTuple,
    PostedEvent.OutputObject
  >;
  getEvent(
    key: "Replied"
  ): TypedContractEvent<
    RepliedEvent.InputTuple,
    RepliedEvent.OutputTuple,
    RepliedEvent.OutputObject
  >;
  getEvent(
    key: "Tipped"
  ): TypedContractEvent<
    TippedEvent.InputTuple,
    TippedEvent.OutputTuple,
    TippedEvent.OutputObject
  >;

  filters: {
    "Disliked(uint256,address)": TypedContractEvent<
      DislikedEvent.InputTuple,
      DislikedEvent.OutputTuple,
      DislikedEvent.OutputObject
    >;
    Disliked: TypedContractEvent<
      DislikedEvent.InputTuple,
      DislikedEvent.OutputTuple,
      DislikedEvent.OutputObject
    >;

    "Liked(uint256,address)": TypedContractEvent<
      LikedEvent.InputTuple,
      LikedEvent.OutputTuple,
      LikedEvent.OutputObject
    >;
    Liked: TypedContractEvent<
      LikedEvent.InputTuple,
      LikedEvent.OutputTuple,
      LikedEvent.OutputObject
    >;

    "Posted(uint256,address,string)": TypedContractEvent<
      PostedEvent.InputTuple,
      PostedEvent.OutputTuple,
      PostedEvent.OutputObject
    >;
    Posted: TypedContractEvent<
      PostedEvent.InputTuple,
      PostedEvent.OutputTuple,
      PostedEvent.OutputObject
    >;

    "Replied(uint256,address,uint256,string)": TypedContractEvent<
      RepliedEvent.InputTuple,
      RepliedEvent.OutputTuple,
      RepliedEvent.OutputObject
    >;
    Replied: TypedContractEvent<
      RepliedEvent.InputTuple,
      RepliedEvent.OutputTuple,
      RepliedEvent.OutputObject
    >;

    "Tipped(uint256,address,uint256)": TypedContractEvent<
      TippedEvent.InputTuple,
      TippedEvent.OutputTuple,
      TippedEvent.OutputObject
    >;
    Tipped: TypedContractEvent<
      TippedEvent.InputTuple,
      TippedEvent.OutputTuple,
      TippedEvent.OutputObject
    >;
  };
}
